let notificationMessage = {
    "text": "Time to add your hours for: ", // add the date here
    "attachments": [
        {
            "text": "Didn't work 8 hours? Click More Info.",
            "fallback": "Unable to Update Daily Timesheet. Please go directly to BambooHR",
            "callback_id": "bambot_daily_hours",
            "color": "#3AA3E3",
            "attachment_type": "default",
            "actions": [
                {
                    "name": "hours",
                    "text": "8 Great Hours",
                    "type": "button",
                    "value": "default",
                    "style": "primary"
                },
                {
                    "name": "hours",
                    "text": "More Info",
                    "type": "button",
                    "value": "custom"
                }
            ]
        }
    ]
}
let dialog = {
    "dialog": {
        "title": "Add Work Hours",
        "submit_label": "Submit",
        "state": "Limo",
        "elements": [
            {
                "type": "text",
                "label": "Hours Worked",
                "name": "hours",
                "placeholder": 8,
                "subtype": "number"
            },
            {
                "type": "textarea",
                "label": "Description of Work",
                "name": "description",
                "optional": "true",
                "placeholder": "What kinda work did you do today rockstar?"
            }
        ]
    }
}

let dateOptions = { 
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', 
    timeZone: 'America/Jamaica', timeZoneName: 'short'
};

function getDateValues(timestamp=null) {
    let today: Date;

    if (timestamp !== null) today = new Date(timestamp * 1000);
    else today = new Date();

    return {
        timestamp: Math.ceil(today.getTime() / 1000),
        localString: today.toLocaleDateString('en-US', dateOptions)
    }
}

let slackResponses = {
    timeTrackingUpdateSuccess: data => {
        return `:smiley: Great! I've added ${data.hours} hours to your timesheet for ` + 
            `<!date^${data.timestamp}^{date_long}|${data.localString}>.`
    },
    timeTrackingUpdateFailed: ':disappointed: Sigh. I was unable to update your timesheet. Visit BambooHR and update manually.',
    notInEmployeeDatabase: ':confounded: Sorry. I was unable to find you in the employee database. Visit BambooHR and update manually.',
    tryAgainLater: ":sweat: I'm currently undable to update your timesheet. Please try again later."
}

let testData = {
    "fields": [
        {
            "id": "displayName",
            "type": "text",
            "name": "Display name"
        },
        {
            "id": "firstName",
            "type": "text",
            "name": "First name"
        },
        {
            "id": "lastName",
            "type": "text",
            "name": "Last name"
        },
        {
            "id": "preferredName",
            "type": "text",
            "name": "Preferred name"
        },
        {
            "id": "gender",
            "type": "gender",
            "name": "Gender"
        },
        {
            "id": "jobTitle",
            "type": "list",
            "name": "Job title"
        },
        {
            "id": "workPhone",
            "type": "text",
            "name": "Work Phone"
        },
        {
            "id": "mobilePhone",
            "type": "text",
            "name": "Mobile Phone"
        },
        {
            "id": "workEmail",
            "type": "email",
            "name": "Work Email"
        },
        {
            "id": "department",
            "type": "list",
            "name": "Department"
        },
        {
            "id": "location",
            "type": "list",
            "name": "Location"
        },
        {
            "id": "division",
            "type": "list",
            "name": "Division"
        },
        {
            "id": "linkedIn",
            "type": "text",
            "name": "LinkedIn URL"
        },
        {
            "id": "workPhoneExtension",
            "type": "text",
            "name": "Work Ext."
        },
        {
            "id": "photoUploaded",
            "type": "bool",
            "name": "Employee photo exists"
        },
        {
            "id": "photoUrl",
            "type": "url",
            "name": "Employee photo url"
        },
        {
            "type": "bool",
            "name": "",
            "id": "canUploadPhoto"
        }
    ],
    "employees": [
        {
            "id": "12",
            "displayName": "Akil Aikman",
            "firstName": "Akil",
            "lastName": "Aikman",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Consultant II",
            "workPhone": "8766672327",
            "mobilePhone": "876 5316020",
            "workEmail": "aaikman@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": "Hopskip Drive",
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/12-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "19",
            "displayName": "Janice Alexander",
            "firstName": "Janice",
            "lastName": "Alexander",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Marketing Specialist",
            "workPhone": "8766672327",
            "mobilePhone": "876 4895165",
            "workEmail": "jalexander@qualityworkscg.com",
            "department": "Operations",
            "location": "Jamaica",
            "division": "Internal",
            "linkedIn": "https://www.linkedin.com/in/janice-alexander-52aa9a3b/",
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/19-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "29",
            "displayName": "Danielle Bandoo",
            "firstName": "Danielle",
            "lastName": "Bandoo",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "HR Intern",
            "workPhone": "8766672327",
            "mobilePhone": "876 4450681",
            "workEmail": "dbandoo@qualityworkscg.com",
            "department": "Operations",
            "location": "Jamaica",
            "division": null,
            "linkedIn": "https://www.linkedin.com/in/danielle-bandoo-13aa1512b/?midToken=AQFixaKhbcJMZA&trk=eml-email_type_messaging_digest-header-23-profile&trkEmail=eml-email_type_messaging_digest-header-23-profile-null-8vpyta~jlhcxm42~11-null-neptune%2Fprofile~vanity%2Evi",
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/29-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "15",
            "displayName": "Shervain Barrett",
            "firstName": "Shervain",
            "lastName": "Barrett",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Consultant II",
            "workPhone": "8766672327",
            "mobilePhone": "876 3875830",
            "workEmail": "sbarrett@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/15-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "2",
            "displayName": "POOH BELGIUM",
            "firstName": "POOH",
            "lastName": "BELGIUM",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": null,
            "workPhone": null,
            "mobilePhone": null,
            "workEmail": "panda@bamboohr.com",
            "department": null,
            "location": null,
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/2-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "13",
            "displayName": "Danielle Boothe",
            "firstName": "Danielle",
            "lastName": "Boothe",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Consultant II",
            "workPhone": "8766672327",
            "mobilePhone": "876 4364003",
            "workEmail": "dboothe@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/13-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "20",
            "displayName": "Khadijah Brown",
            "firstName": "Khadijah",
            "lastName": "Brown",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Consultant II",
            "workPhone": "8766689974",
            "mobilePhone": "876 4720460",
            "workEmail": "kbrown@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/20-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "1",
            "displayName": "Kaysia Campbell-Palmer",
            "firstName": "Kaysia",
            "lastName": "Campbell-Palmer",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "HR Specialist",
            "workPhone": "8766672327",
            "mobilePhone": "876 5933724",
            "workEmail": "kcampbell@qualityworkscg.com",
            "department": "Operations",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/1-3-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "3",
            "displayName": "Orane Findley",
            "firstName": "Orane",
            "lastName": "Findley",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Senior Consultant I",
            "workPhone": "8766672327",
            "mobilePhone": "876 4883907",
            "workEmail": "ofindley@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": "Postured",
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/3-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "33",
            "displayName": "Brendan Flannery",
            "firstName": "Brendan",
            "lastName": "Flannery",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Principal delivery Consultant",
            "workPhone": null,
            "mobilePhone": null,
            "workEmail": "bflannery@qualityworkscg.com",
            "department": "Technology",
            "location": "USA",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": false,
            "photoUrl": "https://qualityworksconsulting.bamboohr.com/images/photo_placeholder.gif",
            "canUploadPhoto": 0
        },
        {
            "id": "4",
            "displayName": "Dimitri Harding",
            "firstName": "Dimitri",
            "lastName": "Harding",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Lead Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "8764546891",
            "workEmail": "dharding@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": "https://www.linkedin.com/in/dimitriharding/",
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/4-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "9",
            "displayName": "Warren Harding",
            "firstName": "Warren",
            "lastName": "Harding",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Lead Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "876 7924992",
            "workEmail": "wharding@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/9-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "23",
            "displayName": "Orandi Harris",
            "firstName": "Orandi",
            "lastName": "Harris",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Consultant I",
            "workPhone": "8766672327",
            "mobilePhone": "876 3395201",
            "workEmail": "oharris@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/23-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "11",
            "displayName": "Sheyinka Harry",
            "firstName": "Sheyinka",
            "lastName": "Harry",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Consultant II",
            "workPhone": "8766672327",
            "mobilePhone": "876 8734739",
            "workEmail": "sharry@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/11-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "18",
            "displayName": "Claudine James-Johnson",
            "firstName": "Claudine",
            "lastName": "James-Johnson",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Office Assistant",
            "workPhone": "8766672327",
            "mobilePhone": "8767756042",
            "workEmail": null,
            "department": "Operations",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/18-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "17",
            "displayName": "Ria Joseph",
            "firstName": "Ria",
            "lastName": "Joseph",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Consultant II",
            "workPhone": "8766672327",
            "mobilePhone": "876 8950092",
            "workEmail": "rjoseph@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/17-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "32",
            "displayName": "Stacy Kirk",
            "firstName": "Stacy",
            "lastName": "Kirk",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Chief Executive Officer",
            "workPhone": "8766672327",
            "mobilePhone": "13104675122",
            "workEmail": "skirk@qualityworkscg.com",
            "department": "Operations",
            "location": "USA",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/32-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "34",
            "displayName": "Mannin Marsh",
            "firstName": "Mannin",
            "lastName": "Marsh",
            "preferredName": "Mannin",
            "gender": "Male",
            "jobTitle": "Consultant I",
            "workPhone": null,
            "mobilePhone": "‭+1 (876) 784-4168",
            "workEmail": "mmarsh@qualityworkscg.com",
            "department": "Technology",
            "location": "Kingston",
            "division": null,
            "linkedIn": "www.linkedin.com/in/manheen/",
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/34-1-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "24",
            "displayName": "Yanika Miller",
            "firstName": "Yanika",
            "lastName": "Miller",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Associate Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "876 3463913",
            "workEmail": "ymiller@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/24-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "25",
            "displayName": "Nyran Moodie",
            "firstName": "Nyran",
            "lastName": "Moodie",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Consultant I",
            "workPhone": "8766672327",
            "mobilePhone": "876 4429063",
            "workEmail": "nmoodie@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/25-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "26",
            "displayName": "Janique Morris",
            "firstName": "Janique",
            "lastName": "Morris",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Consultant I",
            "workPhone": "8766672327",
            "mobilePhone": "876 3614244",
            "workEmail": "jmorris@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/26-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "5",
            "displayName": "Martin Morrison",
            "firstName": "Martin",
            "lastName": "Morrison",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Senior Consultant II",
            "workPhone": "8766672327",
            "mobilePhone": "876 7894593",
            "workEmail": "mmorrison@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/5-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "6",
            "displayName": "Julia Pottinger",
            "firstName": "Julia",
            "lastName": "Pottinger",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Senior Consultant I",
            "workPhone": "8766672327",
            "mobilePhone": "876 5714140",
            "workEmail": "jpottinger@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/6-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "14",
            "displayName": "Jamel Reid",
            "firstName": "Jamel",
            "lastName": "Reid",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Lead Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "876 2796337",
            "workEmail": "jreid@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": "https://www.linkedin.com/in/jamelnreid/",
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/14-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "7",
            "displayName": "Gavin Samuels",
            "firstName": "Gavin",
            "lastName": "Samuels",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Lead Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "876 4672292",
            "workEmail": "gsamuels@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": "https://www.linkedin.com/in/samuelsgavin/",
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/7-1-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "27",
            "displayName": "Mikhail Shaw",
            "firstName": "Mikhail",
            "lastName": "Shaw",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Associate Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "876 5851482",
            "workEmail": "mshaw@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/27-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "10",
            "displayName": "Brittany Stewart",
            "firstName": "Brittany",
            "lastName": "Stewart",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Associate Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "876 3911909",
            "workEmail": "bbird@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": "https://www.linkedin.com/in/brittanyleebird/",
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/10-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "31",
            "displayName": "Orlando Stewart",
            "firstName": "Orlando",
            "lastName": "Stewart",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Site Coordinator/Driver",
            "workPhone": "8766672327",
            "mobilePhone": "876 5210582",
            "workEmail": null,
            "department": "Operations",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/31-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "8",
            "displayName": "Shantel Stewart",
            "firstName": "Shantel",
            "lastName": "Stewart",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Senior Consultant I",
            "workPhone": "8766672327",
            "mobilePhone": "876 8492813",
            "workEmail": "sstewart@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/8-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "30",
            "displayName": "Nyoka Whyne",
            "firstName": "Nyoka",
            "lastName": "Whyne",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Marketing Intern",
            "workPhone": "8766672327",
            "mobilePhone": "876 5839492",
            "workEmail": "nwhyne@qualityworkscg.com",
            "department": "Operations",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/30-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "28",
            "displayName": "Kimberley Whyte",
            "firstName": "Kimberley",
            "lastName": "Whyte",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Associate Consultant",
            "workPhone": "8766672327",
            "mobilePhone": "876 4074715",
            "workEmail": "kwhyte@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/28-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "22",
            "displayName": "Itasha Williams",
            "firstName": "Itasha",
            "lastName": "Williams",
            "preferredName": null,
            "gender": "Female",
            "jobTitle": "Executive Assistant",
            "workPhone": "8766672327",
            "mobilePhone": "876 8184485",
            "workEmail": "iwilliams@qualityworkscg.com",
            "department": "Operations",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/22-0-1.jpg",
            "canUploadPhoto": 0
        },
        {
            "id": "21",
            "displayName": "Damian Wynter",
            "firstName": "Damian",
            "lastName": "Wynter",
            "preferredName": null,
            "gender": "Male",
            "jobTitle": "Consultant I",
            "workPhone": "8766672327",
            "mobilePhone": "876 4825627",
            "workEmail": "dwynter@qualityworkscg.com",
            "department": "Technology",
            "location": "Jamaica",
            "division": null,
            "linkedIn": null,
            "workPhoneExtension": null,
            "photoUploaded": true,
            "photoUrl": "https://3ca5bb5d424e5211335f-88de4a379b98bbb26cd970bd6160ec7f.ssl.cf1.rackcdn.com/photos/21-0-1.jpg",
            "canUploadPhoto": 0
        }
    ]
}

export { notificationMessage };
export { dialog };
export { getDateValues };
export { slackResponses };
export { testData };